### ISSUE TITLE
Exception in ProgramFactory, public static T Create<T>() when starting any of examples

### ISSUE THREAD

**Issue by uzername** [opentk/ObjectTK#7]
Whenever I try to start any of the examples from tree list, a window with white rectangle on black background briefly shows and I get an exception

```
An unhandled exception of type 'System.Exception' occurred in ObjectTK.dll
Invalid effect key: 330

'Examples.exe' (CLR v4.0.30319: Examples.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

Unhandled Exception: System.Exception: Invalid effect key: 330 ---> System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ObjectTK.Shaders.ProgramFactory.GetShaderSource(String effectKey, List`1 included) in C:\ObjectTK\LIB\ObjectTK\ObjectTK\Shaders\ProgramFactory.cs:line 107
   --- End of inner exception stack trace ---
   at ObjectTK.Shaders.ProgramFactory.GetShaderSource(String effectKey, List`1 included) in C:\ObjectTK\LIB\ObjectTK\ObjectTK\Shaders\ProgramFactory.cs:line 113
   at ObjectTK.Shaders.ProgramFactory.GetShaderSource(String effectKey, List`1 included) in C:\ObjectTK\LIB\ObjectTK\ObjectTK\Shaders\ProgramFactory.cs:line 154
   at ObjectTK.Shaders.ProgramFactory.Create[T]() in C:\ObjectTK\LIB\ObjectTK\ObjectTK\Shaders\ProgramFactory.cs:line 85
   at Examples.BasicExamples.SkyboxExample.OnLoad(Object sender, EventArgs e) in C:\ObjectTK\LIB\ObjectTK\Examples\BasicExamples\SkyboxExample.cs:line 32
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at Examples.ExampleBrowser.RunExample(TreeNode node) in C:\ObjectTK\LIB\ObjectTK\Examples\ExampleBrowser.cs:line 70
   at Examples.ExampleBrowser.TreeViewExamples_NodeMouseDoubleClick(Object sender, TreeNodeMouseClickEventArgs e) in C:\ObjectTK\LIB\ObjectTK\Examples\ExampleBrowser.cs:line 57
   at System.Windows.Forms.TreeView.OnNodeMouseDoubleClick(TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Examples.ExampleBrowserEntry.Main() in C:\ObjectTK\LIB\ObjectTK\Examples\ExampleBrowserEntry.cs:line 17
The program '[10176] Examples.exe' has exited with code 0 (0x0).

**Comment by uzername** [comment]
I have messed up with shader file syntax. It should look like:
**-- <shader type identifier>**
#version 330

... shader code ...

**-- <shader type identifier>**
#version 330

... code ...
